---
title: "phenotype correlation in UKBB"
output: html_document
date: "2025-01-17"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = F)
library(ppcor)
```

##Functions
```{r,echo=FALSE,eval=FALSE}
phenocor<-function(data1,data2,covarf,sample){ #with covariates
  if(any(!colnames(data1)==colnames(data2))){
    stop("Error: unmatched trait.")
  }
  if(any(!rownames(data1)==rownames(data2))){
    stop("Error: unmatched sample between 2 traits.")
  }
  if(any(!rownames(data1)==covarf$FID)){
    stop("Error: unmatched sample between trait and covar.")
  }
  result<-NULL
  for (i in 1:ncol(data1)){
    if(i %% 10==0){
      cat(i,'\n')
    }
    covarf.scaled<-apply(subset(covarf,FID %in% sample)[,c('age','sex')],2,scale)
    tmp<-data.frame(DTI=subset(data1,row.names(data1) %in% sample)[,i],
                    rfMRI=subset(data2,row.names(data2) %in% sample)[,i],covarf.scaled) #covariates
    tmp<-tmp[!is.na(tmp$DTI),]
    test<-pcor.test(tmp$DTI,tmp$rfMRI,tmp[,3:4],method='spearman')
    result<-rbind(result,c(test$estimate,test$p.value))
  }
  result<-data.frame(result)
  colnames(result)<-c('rho','p')
  result$trait<-colnames(data1)
  return(result)
}
```

## Calculate phenotype correlations
```{r phenocor,echo=FALSE,eval=FALSE}
load('pheno.Combat.rda')
covar<-read.delim('covar.33716.txt')
pthreshold<-0.05/(413+872)

result.topo<-phenocor(DTItopo,rfMRItopo,covar,rownames(DTItopo))
result.edge<-phenocor(SC,FC,covar,rownames(SC))

result<-rbind(result.topo,result.edge)
result$group<-c(rep('topo',nrow(result.topo)),rep('edge',nrow(result.edge)))
write.table(result,'phenocor.txt',quote = F,sep="\t",row.names = F)
```
